const languageId = {
    zh: 0,
    en: 1,
}
const language = {
    language: ['语言','Language'],
    lan: ['中文','English'],
    tilte: ['在线棋类游戏对战平台','Online Chess Game Platform'],
    quickStart: ['快速开始','Quick Start'],
    createRoom: ['创建房间','Create Room'],
    roomList: ['房间列表','Room List'],
    loginOut: ['退出登录','Login Out'],
    login: ['登录','Login'],
    confirm: ['确定','Confirm'],
    cancel: ['取消','Cancel'],
    guestLogin: ['游客登录','Guest Login'],
    first: ['先手','First'],
    second: ['后手','Second'],
    random: ['随机','Random'],
    room: ['房间','Room'],
    host: ['房主','Host'],
    chooseGame: ['选择游戏', 'Choose Game'],
    chooseYourTurn: ['选择先后手','Choose Your Turn'],
    pleaseLogin: ['请先登录','Please Login'],
    pleaseChooseGame: ['请选择游戏','Please Choose Game'],
    noRoom: ['暂无房间','No Room'],
    beKicked: ['你已被踢出房间','You have been kicked out of the room'],
    notInGame: ['你不在游戏中','You are not in the game'],
    loginSucess: ['登录成功','Login Sucess'],
    loginOutSucess: ['登出成功','Login Out Sucess'],
    amount: ['数量','Amount'],
    watch: ['观战','Watch'],
    kickOut: ['踢出','Kick Out'],
    chooseSlot: ['选择位置','Choose Slot'],
    start: ['开始','Start'],
    number: ['序号','Number'],
    name: ['名称','Name'],
    status: ['状态','Status'],
    type: ['类型','Type'],
    operate: ['操作','Operate'],
    fresh: ['刷新','Fresh'],
    join: ['加入','Join'],
    yourTurn: ['轮到你了: ','Your Turn: ' ],
    opponentTurn: ['对手回合','Opponent Turn'],
    restTime: [(time:number)=>`剩余${time}秒`,(time:number)=>`Rest ${time} Seconds`],
    backToHome: ['返回主页','Back To Home'],
    returnRoom: ['返回房间','Return Room'],
    noWinner: ['平局','No Winner'],
    winner: ['获胜','is winner'],
    gameEnd: ['游戏结束','Game End'],
    gobang: ['五子棋','Gobang'],
    

}
export {languageId,language};